apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "proxy-chart.fullname" . }}
  labels:
    {{- include "proxy-chart.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "proxy-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "proxy-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "proxy-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.proxyConfig.proxyMetricsPort }}
              protocol: TCP
            - name: cql
              containerPort: {{ .Values.proxyConfig.proxyQueryPort }}
              protocol: TCP
          env:
            - name: PROXY_METRICS_PORT
              value: "{{ .Values.proxyConfig.proxyMetricsPort }}"
            - name: PROXY_QUERY_PORT
              value: "{{ .Values.proxyConfig.proxyQueryPort }}"
          envFrom:
            - configMapRef:
                name: "{{ include "proxy-chart.fullname" . }}-configmap"
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
