apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "proxy-chart.fullname" . }}-configmap"
data:

  { { - if .Values.proxyConfig.proxyIndex } }
  PROXY_INDEX: "{{ .Values.proxyConfig.proxyIndex }}"
  { { - end } }

  { { - if .Values.proxyConfig.proxyInstanceCount } }
  PROXY_INSTANCE_COUNT: "{{ .Values.proxyConfig.proxyInstanceCount }}"
  { { - end } }

  { { - if .Values.proxyConfig.proxyAddresses } }
  PROXY_ADDRESSES: "{{ .Values.proxyConfig.proxyAddresses }}"
  { { - end } }

  { { - if .Values.proxyConfig.originEnableHostAssignment } }
  ORIGIN_ENABLE_HOST_ASSIGNMENT: "{{ .Values.proxyConfig.originEnableHostAssignment }}"
  { { - end } }

  { { - if .Values.proxyConfig.targetEnableHostAssignment } }
  TARGET_ENABLE_HOST_ASSIGNMENT: "{{ .Values.proxyConfig.targetEnableHostAssignment }}"
  { { - end } }

  ORIGIN_CASSANDRA_CONTACT_POINTS: "{{ .Values.proxyConfig.originCassandraContactPoints }}"
  ORIGIN_CASSANDRA_USERNAME: "{{ .Values.proxyConfig.originCassandraUsername }}"
  ORIGIN_CASSANDRA_PASSWORD: "{{ .Values.proxyConfig.originCassandraPassword }}"

  {{- if .Values.proxyConfig.originCassandraPort }}
  ORIGIN_CASSANDRA_PORT: "{{ .Values.proxyConfig.originCassandraPort }}"
  {{- end }}

  TARGET_CASSANDRA_CONTACT_POINTS: "{{ .Values.proxyConfig.targetCassandraContactPoints }}"
  TARGET_CASSANDRA_USERNAME: "{{ .Values.proxyConfig.targetCassandraUsername }}"
  TARGET_CASSANDRA_PASSWORD: "{{ .Values.proxyConfig.targetCassandraPassword }}"

  {{- if .Values.proxyConfig.targetCassandraPort }}
  TARGET_CASSANDRA_PORT: "{{ .Values.proxyConfig.targetCassandraPort }}"
  {{- end }}

  {{- if .Values.proxyConfig.clusterConnectionTimeoutMs }}
  CLUSTER_CONNECTION_TIMEOUT_MS: "{{ .Values.proxyConfig.clusterConnectionTimeoutMs }}"
  {{- end }}

  {{- if .Values.proxyConfig.heartbeatIntervalMs }}
  HEARTBEAT_INTERVAL_MS: "{{ .Values.proxyConfig.heartbeatIntervalMs }}"
  {{- end }}

  {{- if .Values.proxyConfig.heartbeatRetryIntervalMinMs }}
  HEARTBEAT_RETRY_INTERVAL_MIN_MS: "{{ .Values.proxyConfig.heartbeatRetryIntervalMinMs }}"
  {{- end }}

  {{- if .Values.proxyConfig.heartbeatRetryIntervalMaxMs }}
  HEARTBEAT_RETRY_INTERVAL_MAX_MS: "{{ .Values.proxyConfig.heartbeatRetryIntervalMaxMs }}"
  {{- end }}

  {{- if .Values.proxyConfig.heartbeatRetryBackoffFactor }}
  HEARTBEAT_RETRY_BACKOFF_FACTOR: "{{ .Values.proxyConfig.heartbeatRetryBackoffFactor }}"
  {{- end }}

  {{- if .Values.proxyConfig.heartbeatFailureThreshold }}
  HEARTBEAT_FAILURE_THRESHOLD: "{{ .Values.proxyConfig.heartbeatFailureThreshold }}"
  {{- end }}

  {{- if .Values.proxyConfig.originBucketsMs }}
  ORIGIN_BUCKETS_MS: "{{ .Values.proxyConfig.originBucketsMs }}"
  {{- end }}

  {{- if .Values.proxyConfig.targetBucketsMs }}
  TARGET_BUCKETS_MS: "{{ .Values.proxyConfig.targetBucketsMs }}"
  {{- end }}

  {{- if .Values.proxyConfig.enableMetrics }}
  ENABLE_METRICS: "{{ .Values.proxyConfig.enableMetrics }}"
  {{- end }}

  {{- if .Values.proxyConfig.maxClientsThreshold }}
  MAX_CLIENTS_THRESHOLD: "{{ .Values.proxyConfig.maxClientsThreshold }}"
  {{- end }}

  {{- if .Values.proxyConfig.forwardReadsToTarget }}
  FORWARD_READS_TO_TARGET: "{{ .Values.proxyConfig.forwardReadsToTarget }}"
  {{- end }}

  {{- if .Values.proxyConfig.requestTimeoutMs }}
  REQUEST_TIMEOUT_MS: "{{ .Values.proxyConfig.requestTimeoutMs }}"
  {{- end }}

  DEBUG: "{{ .Values.proxyConfig.debug }}"
