apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: cloud-gate
  labels:
    app: cloud-gate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-gate
  template:
    metadata:
      labels:
        app: cloud-gate
    spec:
      containers:
        - name: cloud-gate
          image: gcr.io/astrae2dv4yertwzx3d4hdbr6llxm/cloud-gate
          resources:
            requests:
                cpu: 25m
                memory: 50Mi
          ports:
          - name: proxy-cql
            containerPort: 14002
            protocol: TCP
          - name: proxy-metrics
            containerPort: 14001
            protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 14002
#      imagePullSecrets:
#        - name: {{.DockerRegistryName}}
